### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by Michalis2515** [soonaverse/soonaverse-dao#755] opened 2022-06-01 17:34 UTC
### Discord Name

Michalis#2515

### Soonaverse Profile Id

0xB3f7aF5E7c65fCbB32B5d597d9C091C92467369a

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

1.6.0

### Payment Sent to Address

iota1qptagkta6g07jgwjrjk3j6z2as2s2hvq3m6wfjs6kr5sfgwdx2trqxa9n8d

### Amount Sent

198.00 Mi	

### Payment Message Id

c43d7d9a9505174b91fd223b9ff957d8823fe0a63c01ea557eaec2f99138297b

### NFT Id

soon token

### Comments

```shell
Hello.  Was not returned miota from the purchase of soon tokens.
```

**Comment by adamunchained** [comment] 2022-06-01 20:49
For some reason this person didn't end up with credit. There are only two transactions. Also see attached distribution. No refunds.

I think the issue here is because they made the payment during PROCESSING or pre_mint? This should result in automatic credit. 

<img width="1407" alt="Screen Shot 2022-06-01 at 1 45 57 PM" src="https://user-images.githubusercontent.com/130610/171498907-6f7334c3-1e47-4640-a5e9-24b5a391a72d.png">

```
"0x10936e5a4a0b12cb793d7b28b8a1a68b71856280": {
            "createdOn": {
                "__datatype__": "timestamp",
                "value": "2022-05-26T20:14:03.700Z"
            },
            "member": "0xb3f7af5e7c65fcbb32b5d597d9c091c92467369a",
            "payload": {
                "amount": 198000000,
                "chainReference": "c43d7d9a9505174b91fd223b9ff957d8823fe0a63c01ea557eaec2f99138297b",
                "collection": null,
                "invalidPayment": false,
                "nft": null,
                "reconciled": true,
                "sourceAddress": "iota1qqxujtpc36xxj8kuzcutwhw3h5eaeehwkgawpf6rhg2sns9rjpdyq76jg9l",
                "sourceTransaction": [
                    "0xb3f7af5e7c65fcbb32b5d597d9c091c92467369a_0x00defdc5a919182806f33b4be3b0782f46bfcdb0"
                ],
                "targetAddress": "iota1qptagkta6g07jgwjrjk3j6z2as2s2hvq3m6wfjs6kr5sfgwdx2trqxa9n8d",
                "token": "0x00defdc5a919182806f33b4be3b0782f46bfcdb0",
                "void": false
            },
            "space": "0x5fcc5562385e6c2f6b0a5934280e5d11274f8e07",
            "type": "PAYMENT",
            "uid": "0x10936e5a4a0b12cb793d7b28b8a1a68b71856280",
            "__collections__": {}
        },
        "0xb3f7af5e7c65fcbb32b5d597d9c091c92467369a_0x00defdc5a919182806f33b4be3b0782f46bfcdb0": {
            "createdOn": {
                "__datatype__": "timestamp",
                "value": "2022-05-26T20:09:22.853Z"
            },
            "linkedTransactions": [
                "0x10936e5a4a0b12cb793d7b28b8a1a68b71856280"
            ],
            "member": "0xb3f7af5e7c65fcbb32b5d597d9c091c92467369a",
            "payload": {
                "amount": 1.8,
                "beneficiary": "space",
                "beneficiaryAddress": "iota1qretvaxgprw8qehu8h27re4t9jjpx0ygwtj9jxxy0zyuhs36cxv0stkjy0y",
                "beneficiaryUid": "0x5fcc5562385e6c2f6b0a5934280e5d11274f8e07",
                "chainReference": null,
                "expiresOn": {
                    "__datatype__": "timestamp",
                    "value": "2022-05-27T06:00:00Z"
                },
                "reconciled": false,
                "targetAddress": "iota1qptagkta6g07jgwjrjk3j6z2as2s2hvq3m6wfjs6kr5sfgwdx2trqxa9n8d",
                "token": "0x00defdc5a919182806f33b4be3b0782f46bfcdb0",
                "type": "TOKEN_PURCHASE",
                "validationType": 1,
                "void": true
            },
            "space": "0x5fcc5562385e6c2f6b0a5934280e5d11274f8e07",
            "type": "ORDER",
            "uid": "0xb3f7af5e7c65fcbb32b5d597d9c091c92467369a_0x00defdc5a919182806f33b4be3b0782f46bfcdb0",
            "__collections__": {}
        }
        ```

**Comment by adamunchained** [comment] 2022-06-01 20:50
@boldizsar-a-mezei - marking as hotfix (merge to master)

**Comment by boldizsar-a-mezei** [comment] 2022-06-01 21:01
@adamunchained 
There is a logic for this already in place but it was merged 2 days ago, however this transaction happened on the 26th. I think the issue is already fixed.
![image](https://user-images.githubusercontent.com/65147512/171500840-d572042f-aab7-4241-9740-4a4d385f0dc1.png)

**Comment by adamunchained** [comment] 2022-06-01 21:12
ah ok! I'll proceed with refund manually.

@Michalis2515 - you should receive refund now. See: https://thetangle.org/message/b17de50b7aefe5480d59cd54668f3bec927a0b421c1fc8c1991a5a2108e39588

**Closed by adamunchained** 2022-06-01 21:12 UTC
Labels: bug, Payment Issue

**Comment by Michalis2515** [comment] 2022-06-02 04:50
Thank you for your help. 

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Πέμ, 2 Ιουν, 2022 στις 0:12, ο ***@***.***> έγραψε:   


ah ok! I'll proceed with refund manually.

@Michalis2515 - you should receive refund now. See: https://thetangle.org/message/b17de50b7aefe5480d59cd54668f3bec927a0b421c1fc8c1991a5a2108e39588
