### ISSUE TITLE
SFT sale 'one per member' not blocking users from purchasing more NFTs

### ISSUE THREAD

**Issue by antonionardella** [soonaverse/soonaverse-dao#705] opened 2022-05-17 13:04 UTC
**Describe the bug**
I set a collection as 'one per member' 
![image](https://user-images.githubusercontent.com/7383572/168816870-814fb26a-1bd2-42a7-805c-8dbc1bfec2ad.png)

Although I can open an order and try to buy another one:
![image](https://user-images.githubusercontent.com/7383572/168816990-ba203402-195b-4850-8975-983c878b51ba.png)

I did not try to complete the order since I did not want to mess up the sale.

I tried to use the staging site, but there the order window does not open, so I cannot complete the purchase to see if it works at all.

**To Reproduce**
1. Set up a collection with 'one per member' option
2. Buy SFT once
3. Try to buy it again

**Expected behavior**
A message that informs the user that a second purchase is not possible, like this
![image](https://user-images.githubusercontent.com/7383572/168965592-7a11c748-555f-4847-8a4d-cdd5dae16ee3.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

Best,
Antonio

**Comment by adamunchained** [comment] 2022-05-28 13:49
Yeah the validation is only on the backend. It would still show as purchasable but it’ll only be disallowed once you hit confirm.

TODO: Let’s make sure buy now is disabled and show pop-up bubble that NFT from the collections was already purchased.

**Comment by adamunchained** [comment] 2023-02-05 18:56
duplicate of https://github.com/soonaverse/soonaverse-dao/issues/699

It'll be discussed there further

**Closed by adamunchained** 2023-02-05 18:56 UTC
Labels: bug, needs further review
