### ISSUE TITLE
new discord username format without # is not supported

### ISSUE THREAD

**Issue by IOTAPUNKS** [soonaverse/soonaverse-dao#1162] opened 2023-06-15 06:32 UTC
Since a short time Discord supports a new username format. It is no longer necessary to use a # in the username. Soonaverse does not support this new format yet. Please adjust the input field in Soonaverse to accept usernames without #.
![username](https://github.com/soonaverse/soonaverse-dao/assets/36330992/0520dc34-6d57-457c-acf8-f5e59ac9da54)

**Comment by renewid** [comment] 2023-06-15 06:41
can confirm this. cant change it to r3new

**Comment by adamunchained** [comment] 2023-07-03 04:30
closing as duplicate of #1159

**Closed by adamunchained** 2023-07-03 04:30 UTC
Labels: bug
