### ISSUE TITLE
Back to profile leads to a 404 error

### ISSUE THREAD

**Issue by m3rlin5ky** [soonaverse/soonaverse-dao#967] opened 2022-12-08 12:46 UTC
**Describe the bug**
Back to profile leads to a 404 error after visiting the "Activity-My Staking" site within the personal profile on the Soonaverse homepage.

**To Reproduce**
1. Go to "My Profile"
2. Click on 'Activity'
3. Click on 'View All' (My Staking)
4. Click on 'SOON Token'
5. Click on 'Back Profile'
6. See error

**Expected behavior**
Back to the profile page.

**Screenshots**
![image](https://user-images.githubusercontent.com/43293035/206449143-a5789d2d-4990-4936-aebd-25867914a766.png)
![image](https://user-images.githubusercontent.com/43293035/206449226-98725fa1-e9f8-4aff-981f-d8993198d91f.png)

**Desktop (please complete the following information):**
 - OS: MS Windows 11
 - Google Chrome
 - Version 108.0.5359.99 (64-Bit)

**Comment by adamunchained** [comment] 2022-12-08 17:15
Closing as duplicate of https://github.com/soonaverse/soonaverse-dao/issues/960

**Closed by adamunchained** 2022-12-08 17:15 UTC
Labels: bug
