### ISSUE TITLE
Wrong price displayed in payment confirmation window

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#663] opened 2022-04-20 19:49 UTC
**Describe the bug**
A friend of mine created a collection (https://soonaverse.com/collection/0x720a97bc927a46c130db40d18f94998db5d807bb) and reduced the price after launch from 75 Mi to 37.5 Mi (60/30 with the 20% discount badge).
**Having the badge** I purchased one for 30 Mi and got this confusing price in the screenshot.

Nevertheless 30 Mi were sent from my wallet and he received 30 Mi (28.5 + 1.5 Royalty). Therefore it is not a payment issue imo.

**To Reproduce**
1. Clicked "Buy" 
2. Chose the Firefly-Link for payment (price of 30 Mi was filled in Firefly correctly)
3. Payment was processed
4. The "transaction finished" screen showed the wrong price (see screenshot)

**Expected behavior**
I'd expect the price to be shown like 37.5 Mi (crossed)  -- 30.00 Mi (price after discount)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/104099536/164308558-a49c932e-bebf-4582-9108-83dd39a660a6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home - Version 21H2
 - Browser Firefox
 - Version 99.0.1 (64-Bit)

**Additional context**
This doesn't seem to be limited to the collection above because he told me about the same behavior regarding "TanglePay NFT". But also in that case the payment in the background was correct.

Cheers,
Bananu

**Comment by adamunchained** [comment] 2022-08-25 15:07
duplicate of https://github.com/soonaverse/soonaverse-dao/issues/793

**Closed by adamunchained** 2022-08-25 15:07 UTC
Labels: bug
