### ISSUE TITLE
Not able to change the price of NFTs after collection mint

### ISSUE THREAD

**Issue by AdrienAO** [soonaverse/soonaverse-dao#1027] opened 2023-01-26 08:55 UTC
**Describe the bug**
I minted a collection (https://soonaverse.com/collection/0x0be14781be8d707eb7d7e08cee39895c1c569459) and first bug was that it asked for a MIOTA price (in German at least), although the price is now shown in SMR. Once the collection is minted, we are not able to change the price now. 

**To Reproduce**
1. Go to a 'collection'
2. Click on 'mint collection'
3. Now you can see that you won't be able to change the price.

**Expected behavior**
Be able to change the price for remaining NFTs.

**Screenshots**
<img width="951" alt="Screenshot 2023-01-26 at 09 54 16" src="https://user-images.githubusercontent.com/109960736/214795037-2927dc20-7f4e-4f2e-831e-eb24c4f73207.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment] 2023-01-26 18:30
Yeah the price was never changeable so this is not a bug :) 

Let me think if we still needs this restriction and we might implement an enhancement.

**Comment by AdrienAO** [comment] 2023-01-26 21:55
Well the bug is that it asked for a MIOTA price in DE localization, but the price is actually in SMR.

**Comment by adamunchained** [comment] 2023-04-17 14:45
This has been delivered already. Closing.

**Closed by adamunchained** 2023-04-17 14:45 UTC
Labels: enhancement
